### PR TITLE
Prevents Commands from being garbage collected

### PR DESCRIPTION
**Pull request by restouffer**
I don't know if this will be helpful for #5 or not. If I understand nodelete, this wouldn't cause memory leaks for my team, and I imagine most other teams would be similar. I don't know of any sane paradigm that requires multiplying single-use commands. (If nodelete allows manual deletion with del, even that could be managed.) If this is totally wrong or not the direction you want to go, feel free to decline.

### CODE REVIEW

**Comment by virtuald** [comment]
You would also need to apply this to buttons.

**Comment by virtuald** [comment]
Have you tried compiling this and running it? If not, that's ok, I can try it tonight.

You should merge in master, which will cause pull requests to be built on github actions. https://github.com/robotpy/robotpy-commands-v1/blob/master/.github/workflows/dist.yml#L4

**Comment by restouffer** [comment]
I added the changes from master to my fork, but it fails on the macos-latest build. I haven't tried to build or test it locally.

**Comment by virtuald** [comment]
Yeah, so I fixed the compile error and pushed it to your branch, but unfortunately it still doesn't work:

```
  File "/home/virtuald/.virtualenvs/frc-2020/lib/python3.7/site-packages/wpilib/command/__init__.py", line 4, in <module>
    from ._commands_v1 import (
ImportError: generic_type: type "Command" does not have a non-default holder type while its base "frc::ErrorBase" does
```

The reason for this is because Command et al inherits from ErrorBase and Sendable, both of which are shared_ptr. By setting nodelete, that causes Command to be held by unique_ptr which is different, and leads to that error. It's not totally clear why they need to be the same, but I've ran into this before and it's a bit annoying.

When I first started creating robotpy-build there were a few instances where it made sense to use shared_ptr instead of unique_ptr (or maybe I had to?), so the wpilib classes all default to shared_ptr.

**Comment by virtuald** [comment]
It appears it is possible to make a shared_ptr that never gets deleted by passing a custom deleter to the constructor, so robotpy-build could be extended to do this automatically. Something like:

```
std::shared_ptr<Foo> foo(new Foo(), [](Foo*){});
```

**Comment by virtuald** [comment]
Closed in favor of 8d7968e

**Pull request closed without merging**
