### PR TITLE
Rename protected methods to retain pre-2020 backwards compat

### PR DESCRIPTION
**Pull request by virtuald**
.. ironically a breaking change for 2020 which I don't usually do in the middle of the season, but long term this is better?

@picode98 and @benjiboy50fonz do you have opinions on this? The effect would be most of the command stuff would be back as it was previously, instead of protected methods starting with underscores.

@auscompgeek may also have sage advice.

### CODE REVIEW

**Comment by auscompgeek** [comment]
I think this mostly makes sense: this is, for the most part, the "public" interface.

Might be better to just have a switch at the class level to turn off the protected prefixing though (and/or at the package level).

**Comment by FRC2539** [comment]
We vote to remove the underscores

**Comment by FRC2539** [comment]
Yes, remove in my opinion.

**Comment by picode98** [comment]
For functions like `_execute` and `_isFinished` in `Command`,  implementing them as public members makes more sense to me, especially since the scheduler (an external class) is calling them.

**Pull request merged**
